In [29]:
import gymnasium as gym
import numpy as np
import torch as T
from mlPhil.actor_critic import ActorCritic
from mlPhil.icm import ICM
from mlPhil.memory import Memory
from mlPhil.utils import plot_learning_curve
from minigrid.wrappers import ImgObsWrapper

In [2]:
env = gym.make("CartPole-v1", render_mode="rgb_array")
env.reset()

(array([-0.01118993, -0.00690076,  0.04110985,  0.02690885], dtype=float32),
 {})

In [6]:
env.action_space

Discrete(2)

In [9]:
env.observation_space.shape

(4,)

In [37]:
env = gym.make("MiniGrid-MultiRoom-N4-S5-v0", render_mode="rgb_array")
env = ImgObsWrapper(env)
env.reset()

(array([[[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0],
         [0, 0, 0],
         [0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]],
 
        [[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0],
         [0, 0, 0],
         [0, 0, 0],
         [2, 5, 0],
         [2, 5, 0]],
 
        [[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0],
         [0, 0, 0],
         [0, 0, 0],
         [2, 5, 0],
         [1, 0, 0]],
 
        [[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0],
         [0, 0, 0],
         [0, 0, 0],
         [2, 5, 0],
         [1, 0, 0]],
 
        [[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0],
         [0, 0, 0],
         [0, 0, 0],
         [2, 5, 0],
         [2, 5, 0]],
 
        [[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0],
         [0, 0, 0],
         [0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]],
 
        [[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0],
         [0, 0, 0],
         [0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]]], 

In [14]:
env.action_space

Discrete(7)

In [25]:
env.observation_space

Dict('direction': Discrete(4), 'image': Box(0, 255, (7, 7, 3), uint8), 'mission': MissionSpace(<function MultiRoomEnv._gen_mission at 0x0000023074E19440>, None))

In [33]:
observation, reward, terminated, truncated, info = env.step(env.action_space.sample())

In [35]:
observation.shape

(7, 7, 3)

In [42]:
T.tensor(observation, dtype=T.float)

tensor([[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [2., 5., 0.],
         [4., 0., 1.],
         [2., 5., 0.],
         [2., 5., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [2., 5., 0.],
         [1., 0., 0.],
         [1., 0., 0.],
         [1., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [2., 5., 0.],
         [1., 0., 0.],
         [1., 0., 0.],
         [1., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [2., 5., 0.],
         [1., 0., 0.],
         [1., 0., 0.],
         [1., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [2., 5., 0.],
         [2., 5., 0.],
         [2., 5., 0.],
         [2., 5., 0.]],

        [[0., 0., 0.],